### ISSUE TITLE
can't use api commands - error

### ISSUE THREAD

**Issue by ramboe** [thybag/PHP-SharePoint-Lists-API#62]
this is my code:

include "Thybag\SharePointAPI.php";
include "Thybag\Auth\SharePointOnlineAuth.php";
include "Thybag\Auth\SoapClientAuth.php";
include "Thybag\Auth\StreamWrapperHttpAuth.php";
include "Thybag\Service\ListService.php";
include "Thybag\Service\QueryObjectService.php";

use Thybag\SharePointAPI;
use Thybag\Service\ListService;
use Thybag\Service\QueryObjectService;

$sp = new SharePointAPI('&&', '&&', 'http://localhost/Lists.asmx.xml', TRUE);

$sp->getLists();
-----------------------------------------------------------------------------------------------

trying to execute this, the browser throws the following:

Fatal error: Uncaught exception 'Exception' with message 'Error' in C:\xampp\htdocs\Thybag\Auth\SoapClientAuth.php:130 Stack trace: #0 [internal function]: Thybag\Auth\SoapClientAuth->__doRequest('<?xml version="...', 'http://share.mi...', 'http://schemas....', 1, 0) #1 C:\xampp\htdocs\Thybag\SharePointAPI.php(276): SoapClient->__call('GetListCollecti...', Array) #2 C:\xampp\htdocs\Thybag\SharePointAPI.php(276): Thybag\Auth\SoapClientAuth->GetListCollection() #3 C:\xampp\htdocs\listen.php(19): Thybag\SharePointAPI->getLists() #4 {main} thrown in C:\xampp\htdocs\Thybag\Auth\SoapClientAuth.php on line 130

logging in works fine, but when i actually want to use commands like getLists i get this error. what can i do?

**Comment by jjworld** [comment]
I had a similar issue. I dug into the exception and it was actually error 411 in response to the request in SoapClientAuth.php. Something was amiss in the request length and I simply removed the Content-Length parameter from the __doRequest function and everything seems to work fine. 

I'm running v6.3 on CentOS and Nginx. I suspect Nginx or curl is the culprit but I'd rather change the source code instead of installing Apache or digging deeper into curl. 

I'm not sure if there is a downside to removing the Content-Length parameter in the next release.

**Comment by Urganot** [comment]
I had the same issue and could also fix it by removing the Content-Lenght Header.

**Comment by thybag** [comment]
Hello,

Am assuming this was fixed a while back by https://github.com/thybag/PHP-SharePoint-Lists-API/commit/02e4f64aed630d37966fc3f3c9d34e6a0be88fa1 so am closing for now.
