### ISSUE TITLE
Need ability to pass query options through QueryObjectService

### ISSUE THREAD

**Issue by vz28bh** [thybag/PHP-SharePoint-Lists-API#76]
I am implementing a query to a SP 2013 calendar and in order to get the recurring events I need to pass the query option "<ExpandRecurrence>TRUE</ExpandRecurrence>". In order to do this I would like the "get" function in QueryObjectService to accept an argument for options and pass that to the api read function, like this:

	public function get ($options = NULL) {

		// String = view, array = specific fields
		$view = (sizeof($this->fields) === 0) ? $this->view : $this->fields;
		
		return $this->api->read($this->list_name, $this->limit, $this, $view, NULL, $options);
	}

I'm using the SharePointAPI instead of ListService so I can pass in some raw CAML.

**Comment by thybag** [comment]
Hello,
Thanks for the pull :) 

I hope you don't mind but I tweaked the way the options are set to try and keep in more in line with the other functions in the QueryObjectService.

So you'd call 

`$api->query($list)->options($options_xm)->get();`

rather than

`$api->query($list)->get($options_xml);`
