### ISSUE TITLE
Handling uncaught exceptions

### ISSUE THREAD

**Issue by jvarn** [thybag/PHP-SharePoint-Lists-API#94]
This works like a charm, but I can't work out how to handle exceptions. Specifically, if an incorrect password is specified, I receive the following error:
```
Fatal error: Uncaught exception 'Exception' with message 'The entered and stored passwords do not match. ' in path/Thybag/Auth/SharePointOnlineAuth.php:105 Stack trace: #0 path/Thybag/Auth/SharePointOnlineAuth.php(20): Thybag\Auth\SharePointOnlineAuth->configureAuthCookies('https://afta.sh...') #1 [internal function]: Thybag\Auth\SharePointOnlineAuth->__doRequest('<?xml version="...', 'https://......', 'http://schemas....', 1, 0) #2 path/Thybag/SharePointAPI.php(444): SoapClient->__call('GetListItems', Array) #3 path/Thybag/SharePointAPI.php(444): Thybag\Auth\SharePointOnlineAuth->GetListItems(Object(SoapVar)) #4 path/sharepoint.class.php(23): Thybag\SharePointAPI->read('Active Members') #5 path/index.php(10): SharepointMember->__construct() #6 {main} thrown in path/Thybag/Auth/SharePointOnlineAuth.php on line 105
```
I'd appreciate any advice. Thanks.

**Comment by thybag** [comment]
Hello,

What specifically are you having trouble with? Standard try/catch exception handling should hopefully work as normal. 

I guess the only caveat to that would be, that the library doesn't actually attempt to talk to SP until you attempt to perform an action. So for example if the username/password was wrong, the resulting exception would be thrown by the read/write/do somthing method, rather than the `new SharePointAPI` bit?

```PHP
$sp = new SharePointAPI('<username>', '<password>', '<path_to_WSDL>');
try {
    $sp->read('xyz');
} catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
}
```

**Comment by jvarn** [comment]
That works perfectly. 
Still learning here!
Thank you for your support.
